sudo: required
services:
    - docker

before_install:
    - docker  build -t chandresh/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true chandresh/docker-react npm run test -- --coverage
